# Generated by Django 5.0.7 on 2024-07-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_group_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
